### ISSUE TITLE
Why must the VERSION file be bumped on release?

### ISSUE THREAD

**Issue by zsims** [jimeh/common-flow#6]
Firstly thanks for the great summary. This will be useful for many teams, ours included!

Just wondering around the justification for:

> To create a new release, you MUST create a "version bump" commit which changes the hard-coded version string of the project. The version bump commit MUST have a git tag created on it and named as the exact version string.

This is a MUST, but as far as I can see it doesn't serve a purpose given the releases are tagged. It may also have consequences such as triggering CI again and polluting history.

**Comment by leonklingele** [comment]
Bumping the version file is required for your app to know which version itself is?

**Comment by zsims** [comment]
That's injected at build time for us, nothing to do with our source code. So the build artefacts are stamped (e.g. assembly attributes, or this VERSION file).

**Comment by zsims** [comment]
https://gitversion.readthedocs.io/en/latest/ is a prime and popular example of deriving this at build time, and injecting it into your build process

**Comment by leonklingele** [comment]
> injected at build time

Well, that's exactly what the `VERSION` file is for. How else would you retrieve the version? Manually passing it to the build machinery? Retrieving it from Git?

**Comment by leonklingele** [comment]
Using the Git version is nice, but requires to build from a Git checkout. Don't you want to ship release tarballs without a `.git` folder?

**Comment by jimeh** [comment]
The idea is that there's a hard-coded version in the code-base itself to make it easier to keep track of. I added it to the spec cause most projects I've personally come into contact with typically does this.

However, seeing as that's not the case for everyone, specially not across various languages where you might inject the version number at build time, I'd be more than happy to make the hard-coded version string and the bump version commit either RECOMMENDED or OPTIONAL instead of a MUST.

Thoughts? :)

**Comment by jimeh** [comment]
@leonklingele I would imagine that in @zsims case, they've got a CI/build-server setup that monitors for new git tags matching a `X.X.X` or similar naming pattern, and then runs a build from that tag, injecting the tag name itself as the version number.

**Comment by zsims** [comment]
> not the case for everyone, specially not across various languages where you might inject the version number at build time, I'd be more than happy to make the hard-coded version string and the bump version commit either RECOMMENDED or OPTIONAL instead of a MUST

Yes please! This would cover it. Thanks :)

**Comment by XANi** [comment]
@leonklingele Git can actually generate pretty decent version number

|  tag name | `git describe --tags --always` | `git describe --tags --long` |
|-|-|-|
| v0.0.3 | v0.0.3 | v0.0.3-0-gef84bd6 |
| 2 commits after v0.0.3 | v0.0.3-2-ga35472b | v0.0.3-2-ga35472b |

and it also makes any build made using it instantly recognizable (bug report containing full version will always point to exact commit build was made from and that's helpful if someone is giving a bug report for bleeding edge)

And that way you have no extra clutter in changelog and only one source of "truth" when it comes to version

And if you want to ship tarball, then either `git describe... > VERSION` before packing or 

    git archive --format=tar.gz --prefix=app/ -o app-$(git describe --tags --long).tar.gz HEAD

to make git do that for you

**Comment by jimeh** [comment]
@XANi I agree with everything you said. I believe what you're talking about would work with the spec once the hard-coded version and version bump commit requirements are OPTIONAL. Is that right?

**Comment by XANi** [comment]
I think it should be something like:

* There MUST be one source of truth for version number. 
* It SHOULD be a tag that SHOULD follow semantic versioning.
* If application/build system needs a file with version number it SHOULD be named `VERSION` and MUST contain only version number without any prefix.
* If used, `VERSION` SHOULD be auto-generated during build(and in consequence, be .gitignore-d), but if it is changed manually it MUST be a separate commit with version bump

**Comment by jimeh** [comment]
@XANi Sounds good. I think I'll adopt it lightly so it suggests more that you pick where your source of version truth is, with less of a  push for it to be the git tag. Basically so people are forced to think about and pick whatever works best for the project/language.

With Ruby for example, 99% of gems hard-code the version in the source code like so: https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/version.rb

Typically this is something I see in languages where the distributed project is basically the source code. So in something like Ruby you would hard-code the version and use that as the source of truth. While in something like Go, where the version number is often injected at build-time, that truth can easily be the git tag.

Thoughts?

**Comment by XANi** [comment]
Now that I think about there will be probably more cases where version is just in some language-specific file for build/language reasons, and for same reasons it can't be just `VERSION`. So probably just saying "there MUST be single source of truth for version" without forcing any way to do it would be more universal.

Like in Go example you pretty much *have* to use tags as multiple tools for dependency management use that to pick a version to download

**Comment by jimeh** [comment]
Fixed by PR #12.
